/**
 * src/wasm/index.ts
 *
 * Async wrapper around the Emscripten pixelops WASM module.
 *
 * SETUP REQUIRED — before this module works you must compile the WASM:
 *   npm run build:wasm
 * This generates src/wasm/generated/pixelops.js and pixelops.wasm.
 *
 * Usage:
 *   import { getPixelOps, floodFill, gaussianBlur } from '@/wasm'
 *   const wasmReady = getPixelOps() // call once; subsequent calls return cache
 */

import type { PixelOpsModule, PixelOpsFactory, CurvesHistogramResult } from './types'

// ─── Module singleton ─────────────────────────────────────────────────────────

let _module: PixelOpsModule | null = null
let _initPromise: Promise<PixelOpsModule> | null = null

/** Initialise and return the WASM module (idempotent, cached after first call). */
export async function getPixelOps(): Promise<PixelOpsModule> {
  if (_module) return _module
  if (_initPromise) return _initPromise

  _initPromise = (async () => {
    // Dynamic import so Vite only bundles these when getPixelOps() is called.
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — file is generated by `npm run build:wasm`
    const { default: factory } = (await import('./generated/pixelops.js')) as {
      default: PixelOpsFactory
    }
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — generated asset URL resolved by Vite
    const wasmUrl = (await import('./generated/pixelops.wasm?url')).default as string

    _module = await factory({ locateFile: () => wasmUrl })
    return _module
  })()

  return _initPromise
}

// ─── Memory helpers ───────────────────────────────────────────────────────────

/**
 * Copies `data` into WASM memory, calls `fn(ptr)` which may modify it in-place,
 * then copies the (possibly modified) bytes back out and frees the WASM allocation.
 */
function withInPlaceBuffer(
  m: PixelOpsModule,
  data: Uint8Array,
  fn: (ptr: number) => void
): Uint8Array {
  const ptr = m._malloc(data.byteLength)
  try {
    m.HEAPU8.set(data, ptr)
    fn(ptr)
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(ptr, ptr + data.byteLength)
  } finally {
    m._free(ptr)
  }
}

/**
 * Copies `data` into WASM memory, allocates a separate output buffer,
 * calls `fn(srcPtr, dstPtr)`, then returns the output bytes.
 */
function withSrcDstBuffers(
  m: PixelOpsModule,
  data: Uint8Array,
  dstByteLength: number,
  fn: (srcPtr: number, dstPtr: number) => void
): Uint8Array {
  const srcPtr = m._malloc(data.byteLength)
  const dstPtr = m._malloc(dstByteLength)
  try {
    m.HEAPU8.set(data, srcPtr)
    fn(srcPtr, dstPtr)
    return m.HEAPU8.slice(dstPtr, dstPtr + dstByteLength)
  } finally {
    m._free(srcPtr)
    m._free(dstPtr)
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/** Flood-fill starting at (x, y) with the given RGBA colour.
 *  tolerance: max squared Euclidean distance in RGBA space (0 = exact match). */
export async function floodFill(
  pixels: Uint8Array, width: number, height: number,
  x: number, y: number,
  r: number, g: number, b: number, a: number,
  tolerance = 0
): Promise<Uint8Array> {
  const m = await getPixelOps()
  return withInPlaceBuffer(m, pixels, ptr =>
    m._pixelops_flood_fill(ptr, width, height, x, y, r, g, b, a, tolerance)
  )
}

/** Separable Gaussian blur (in-place). radius controls kernel half-width. */
export async function gaussianBlur(
  pixels: Uint8Array, width: number, height: number, radius: number
): Promise<Uint8Array> {
  const m = await getPixelOps()
  return withInPlaceBuffer(m, pixels, ptr =>
    m._pixelops_gaussian_blur(ptr, width, height, radius)
  )
}

/** Generic 2-D convolution. kernelSize must be odd. src and dst are separate. */
export async function convolve(
  pixels: Uint8Array, width: number, height: number,
  kernel: Float32Array
): Promise<Uint8Array> {
  const m = await getPixelOps()
  const kPtr = m._malloc(kernel.byteLength)
  try {
    m.HEAPF32.set(kernel, kPtr >> 2) // float32 view offset
    const kernelSize = Math.round(Math.sqrt(kernel.length))
    return withSrcDstBuffers(m, pixels, pixels.byteLength, (src, dst) =>
      m._pixelops_convolve(src, dst, width, height, kPtr, kernelSize)
    )
  } finally {
    m._free(kPtr)
  }
}

/** Bilinear resize — produces smooth edges (use for photographs). */
export async function resizeBilinear(
  pixels: Uint8Array, srcWidth: number, srcHeight: number,
  dstWidth: number, dstHeight: number
): Promise<Uint8Array> {
  const m = await getPixelOps()
  return withSrcDstBuffers(m, pixels, dstWidth * dstHeight * 4, (src, dst) =>
    m._pixelops_resize_bilinear(src, srcWidth, srcHeight, dst, dstWidth, dstHeight)
  )
}

/** Nearest-neighbour resize — preserves hard pixel-art edges. */
export async function resizeNearest(
  pixels: Uint8Array, srcWidth: number, srcHeight: number,
  dstWidth: number, dstHeight: number
): Promise<Uint8Array> {
  const m = await getPixelOps()
  return withSrcDstBuffers(m, pixels, dstWidth * dstHeight * 4, (src, dst) =>
    m._pixelops_resize_nearest(src, srcWidth, srcHeight, dst, dstWidth, dstHeight)
  )
}

/** Floyd-Steinberg error-diffusion dithering using the given RGBA palette. */
export async function ditherFloydSteinberg(
  pixels: Uint8Array, width: number, height: number,
  palette: Uint8Array // RGBA entries, palette.length / 4 = paletteSize
): Promise<Uint8Array> {
  const m = await getPixelOps()
  const palPtr = m._malloc(palette.byteLength)
  try {
    m.HEAPU8.set(palette, palPtr)
    return withInPlaceBuffer(m, pixels, ptr =>
      m._pixelops_dither_floyd_steinberg(ptr, width, height, palPtr, palette.length / 4)
    )
  } finally {
    m._free(palPtr)
  }
}

/** Ordered (Bayer) dithering. matrixSize: 2, 4, or 8. */
export async function ditherBayer(
  pixels: Uint8Array, width: number, height: number, matrixSize: 2 | 4 | 8 = 4
): Promise<Uint8Array> {
  const m = await getPixelOps()
  return withInPlaceBuffer(m, pixels, ptr =>
    m._pixelops_dither_bayer(ptr, width, height, matrixSize)
  )
}

/** Median-cut palette quantisation.
 *  Returns an RGBA Uint8Array of `maxColors * 4` bytes
 *  and the actual count of palette entries. */
export async function quantize(
  pixels: Uint8Array, maxColors: number
): Promise<{ palette: Uint8Array; count: number }> {
  const m = await getPixelOps()
  const pixelCount = pixels.length / 4
  const palBuf = new Uint8Array(maxColors * 4)
  const pixPtr = m._malloc(pixels.byteLength)
  const palPtr = m._malloc(palBuf.byteLength)
  try {
    m.HEAPU8.set(pixels, pixPtr)
    const count = m._pixelops_quantize(pixPtr, pixelCount, palPtr, maxColors)
    const palette = m.HEAPU8.slice(palPtr, palPtr + count * 4)
    return { palette, count }
  } finally {
    m._free(pixPtr)
    m._free(palPtr)
  }
}

/** Compute histogram for curves adjustment.
 *  Returns RGB, Red, Green, Blue channel histograms (256 bins each).
 *  Optional selectionMask weights the contribution of each pixel. */
export async function computeHistogramRGBA(
  pixelData: Uint8Array, width: number, height: number,
  mask?: Uint8Array
): Promise<CurvesHistogramResult> {
  const m = await getPixelOps()
  const pixPtr = m._malloc(pixelData.byteLength)
  let maskPtr = 0
  try {
    m.HEAPU8.set(pixelData, pixPtr)
    if (mask) {
      maskPtr = m._malloc(mask.byteLength)
      m.HEAPU8.set(mask, maskPtr)
    }

    // Call WASM function to get histogram buffer pointer.
    const histPtr = m._pixelops_curves_histogram(pixPtr, width, height, maskPtr)
    if (!histPtr) {
      throw new Error('WASM histogram allocation failed')
    }

    // Re-read HEAPF32 in case memory grew.
    const heapf32 = m.HEAPF32
    const histFloatOffset = histPtr >> 2 // Convert byte offset to float32 offset.
    const histogramFloat32 = heapf32.slice(histFloatOffset, histFloatOffset + (4 * 256))

    // Free the histogram buffer returned by WASM.
    m._free(histPtr)

    // Split into separate channels (each 256 float32s)
    const rgb = histogramFloat32.subarray(0, 256)
    const red = histogramFloat32.subarray(256, 512)
    const green = histogramFloat32.subarray(512, 768)
    const blue = histogramFloat32.subarray(768, 1024)

    return { rgb, red, green, blue }
  } finally {
    m._free(pixPtr)
    if (maskPtr) {
      m._free(maskPtr)
    }
  }
}
